export const COURSE_MAPPING_BY_SEMESTER = {
  "Semester 1": {
    'GENERATIVE_AI': 'Introduction to Generative AI',
    'MATHEMATICS': 'Mathematics for Computer Science',
    'BUILD_YOUR_OWN_STATIC_WEBSITE': 'Web Application Development I',
    'COMMUNICATIVE_ENGLISH_FOUNDATION': 'Communication English Foundation',
    'PROGRAMMING_FOUNDATIONS': 'Computer Programming',
    'QUANTITATIVE_APTITUDE': 'Quantitative Aptitude',
  },
  "Semester 2": {
    'WEB_APPLICATION_DEVELOPMENT_2': 'Web Application Development 2',
    'WA2': 'Web Application Development 2',
    'DBMS': 'Database Management Systems',
    'DATABASE_MANAGEMENT': 'Database Management Systems',
    'DATA_STRUCTURES': 'Data Structures',
    'DS': 'Data Structures',
    'NUMERICAL_APTITUDE': 'Numerical Aptitude',
    'NA': 'Numerical Aptitude',
    'QUANTITATIVE_APTITUDE': 'Numerical Aptitude',
    'ENGLISH_ADVANCED': 'English Advanced',
    'EA': 'English Advanced',
    'COMMUNICATIVE_ENGLISH_FOUNDATION': 'English Advanced',
    'LLM': 'Large Language Models',
    'LARGE_LANGUAGE_MODELS': 'Large Language Models',
    'GENERATIVE_AI': 'Large Language Models',
    'PHYSICS': 'Physics',
    'PHY': 'Physics',
    'CHEMISTRY': 'Chemistry',
    'CHE': 'Chemistry',
    'YOGA': 'Yoga',
    'TDP': 'Talent Development Program',
    'HVS': 'Human Values & Ethics',
    'HUMAN_VALUES': 'Human Values & Ethics',
    'ASSESSMENT': 'Assessment',
    'AS': 'Assessment',
    'BUSINESS_ENGLISH': 'Business English',
    'BE': 'Business English',
    'IKS': 'Indian Knowledge System',
    'INDIAN_KNOWLEDGE_SYSTEM': 'Indian Knowledge System',
    'LINEAR_ALGEBRA': 'Linear Algebra & Calculus',
    'LA_C': 'Linear Algebra & Calculus',
    'ENVIRONMENTAL_SCIENCE': 'Environmental Science',
    'ENV': 'Environmental Science',
    'INDIAN_CONSTITUTION': 'Indian Constitution',
    'IC': 'Indian Constitution',
    'LANGUAGE_ELECTIVE': 'Language Elective',
    'LA_E': 'Language Elective',
    'ENGINEERING_DRAWING': 'Engineering Drawing',
    'ED': 'Engineering Drawing',
    'CLOUD_COMPUTING': 'Cloud Computing',
    'CC': 'Cloud Computing',
    'PROGRAMMING_FOUNDATIONS': 'Data Structures',
    'BUILD_YOUR_OWN_STATIC_WEBSITE': 'Web Application Development 2',
    'MATHEMATICS': 'Linear Algebra & Calculus',
  },
};
